// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdjfxfpetzysrdclovkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkamZ4ZnBldHp5c3JkY2xvdmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MTE0NDIsImV4cCI6MjA1Nzk4NzQ0Mn0.OSJOCeWjoEL1mr0NG19MkHK8LdoyiOvX_njfi58IACs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);